# @package _group_
# lr: 0.0001056817476637661
lr: 0.191
metric: ${metric.metric_name}
mode: "max"
seed: 666
debug: True
n_classes: 6
lightning_module_name: src.lightning_classes.lightning_seg.LitSemanticSegmentation
