# @package _group_
data_module_name: src.lightning_classes.datamodule_panda.PANDADataModule
base_image_path: /content/drive/MyDrive/Data/PANDA_data/
train_image_path: train_size128_images/
train_labels_path: train_size128_masks/
train_csv: radbound_train.csv
# train_csv: train.csv
test_csv: test.csv

batch_size: 128
valid_size: 0.2
num_workers: 8
pin_memory: True
load_full_csv: True
